### ISSUE TITLE
Not working on Android 14 device/emulator

### ISSUE THREAD

**Issue by Hari10081999** [jfhr/disablecamera2#1]
Please check this project on android 14 it was crashed.
below android 14 working fine.
please update the code for android 14

**Comment by jfhr** [comment]
Looks like the "device admin" method that the app uses [is deprecated](https://developer.android.com/reference/android/app/admin/DevicePolicyManager#setCameraDisabled(android.content.ComponentName,%20boolean)) and calling `setCameraDisabled()` now throws a `SecurityException` on Android 11+. The alternative is [using a managed device or work profile](https://developers.google.com/android/work/device-admin-deprecation). Idk if that's possible without using some kind of commercial provider :( 

If you know of any way, feel free to open a pull request here. I unfortunately don't have time in the near future to look into it more thoroughly. 

Otherwise, your best bet might be [masking tape](https://en.wikipedia.org/wiki/Masking_tape).
